"""Change publication_year to date

Revision ID: 53ca60fee033
Revises: a40879f2ab41
Create Date: 2025-04-18 15:08:21.890839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ca60fee033'
down_revision = 'a40879f2ab41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('event', 'publication_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('publication_year', sa.INTEGER(), nullable=True))
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
